/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author tic-asisweb01
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imageUsuario = new javax.swing.JLabel();
        imageUsuario1 = new javax.swing.JLabel();
        imageUsuario2 = new javax.swing.JLabel();
        imageUsuario3 = new javax.swing.JLabel();
        imageUsuario4 = new javax.swing.JLabel();
        imageUsuario5 = new javax.swing.JLabel();
        imageServidor = new javax.swing.JLabel();
        imageServidor1 = new javax.swing.JLabel();
        imageServidor2 = new javax.swing.JLabel();
        imageServidor3 = new javax.swing.JLabel();
        imageServidor4 = new javax.swing.JLabel();
        imageDistribucion = new javax.swing.JLabel();
        imageServidor6 = new javax.swing.JLabel();
        imageDistribucion1 = new javax.swing.JLabel();
        imageDistribucion2 = new javax.swing.JLabel();
        imageDistribucion3 = new javax.swing.JLabel();
        imageDistribucion4 = new javax.swing.JLabel();
        imageDistribucion5 = new javax.swing.JLabel();
        imageDistribucion6 = new javax.swing.JLabel();
        imageDistribucion7 = new javax.swing.JLabel();
        imageDistribucion8 = new javax.swing.JLabel();
        imageDistribucion9 = new javax.swing.JLabel();
        imageNucleo = new javax.swing.JLabel();
        imageDistribucion11 = new javax.swing.JLabel();
        imageNucleo1 = new javax.swing.JLabel();
        imageNucleo2 = new javax.swing.JLabel();
        imageDistribucion10 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
        SA = new javax.swing.JLabel();
        SB = new javax.swing.JLabel();
        SC = new javax.swing.JLabel();
        SD = new javax.swing.JLabel();
        SE = new javax.swing.JLabel();
        SF = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        RD1 = new javax.swing.JLabel();
        RD2 = new javax.swing.JLabel();
        RD3 = new javax.swing.JLabel();
        RD4 = new javax.swing.JLabel();
        RD5 = new javax.swing.JLabel();
        RD6 = new javax.swing.JLabel();
        RD7 = new javax.swing.JLabel();
        RD8 = new javax.swing.JLabel();
        RD9 = new javax.swing.JLabel();
        RD10 = new javax.swing.JLabel();
        RD11 = new javax.swing.JLabel();
        RD12 = new javax.swing.JLabel();
        RN1 = new javax.swing.JLabel();
        RN2 = new javax.swing.JLabel();
        RN3 = new javax.swing.JLabel();
        comboBoxDestino = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        iniciar = new javax.swing.JButton();
        comboBoxOrigen = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageUsuario3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageUsuario4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageUsuario5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageServidor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageServidor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageServidor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageServidor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageDistribucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageServidor6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageDistribucion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageNucleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Nucleo.png"))); // NOI18N

        imageDistribucion11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageNucleo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Nucleo.png"))); // NOI18N

        imageNucleo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Nucleo.png"))); // NOI18N

        imageDistribucion10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        SA.setText("Usuario A");

        SB.setText("Usuario B");

        SC.setText("Usuario C");

        SD.setText("Usuario D");

        SE.setText("Usuario E");

        SF.setText("Usuario F");

        RD1.setText("RD1");

        RD2.setText("RD2");

        RD3.setText("RD3");

        RD4.setText("RD4");

        RD5.setText("RD5");

        RD6.setText("RD6");

        RD7.setText("RD7");

        RD8.setText("RD8");

        RD9.setText("RD9");

        RD10.setText("RD10");

        RD11.setText("RD12");

        RD12.setText("RD11");

        RN1.setText("RN1");

        RN2.setText("RN2");

        RN3.setText("RN3");

        comboBoxDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario A", "Usuario B", "Usuario C", "Usuario D", "Usuario E", "Usuario F" }));

        jLabel8.setText("Escoger Usuario Destino");

        jLabel9.setText("Escoger Usuario Origen");

        iniciar.setText("Simular");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });

        comboBoxOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario A", "Usuario B", "Usuario C", "Usuario D", "Usuario E", "Usuario F" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RN1)
                                .addGap(141, 141, 141)))
                        .addComponent(imageDistribucion4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(imageUsuario5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(imageUsuario)
                                        .addComponent(SB)
                                        .addComponent(SC, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(imageServidor3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(imageServidor1))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RD3)
                                            .addComponent(imageDistribucion11))
                                        .addGap(114, 114, 114))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(imageDistribucion3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(imageNucleo2)
                                                .addComponent(RD2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageDistribucion2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RD5)
                                        .addGap(19, 19, 19))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(RN2)
                                .addGap(49, 49, 49))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(iniciar)
                                        .addGap(45, 45, 45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(imageDistribucion1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(RD4)
                                        .addGap(15, 15, 15))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(imageUsuario2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(SA)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imageServidor))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RD1)
                                .addGap(146, 146, 146)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(imageDistribucion6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageDistribucion)
                                    .addComponent(imageNucleo1)
                                    .addComponent(RD8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RN3)
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(imageDistribucion10)
                                        .addGap(59, 59, 59)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(imageDistribucion8)
                                            .addComponent(imageDistribucion7)
                                            .addComponent(imageDistribucion5)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(RD10))
                                    .addComponent(RD11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(imageDistribucion9)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RD12)
                                .addGap(67, 67, 67)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(imageServidor6)
                                        .addGap(18, 18, 18)
                                        .addComponent(imageUsuario3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(SE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imageServidor2)
                                        .addGap(18, 18, 18)
                                        .addComponent(imageUsuario4)))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(SD)
                                        .addGap(110, 110, 110))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SF)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(imageServidor4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(imageUsuario1)))
                                        .addGap(101, 101, 101))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(RD6)
                                .addGap(134, 134, 134)
                                .addComponent(RD9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(RD7)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageNucleo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iniciar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RD6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RD9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(RN3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageNucleo1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RD1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(imageDistribucion1)
                                            .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(68, 68, 68))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RD4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RN1)
                                            .addComponent(imageDistribucion4))))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(RD7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(imageDistribucion)
                                            .addGap(36, 36, 36)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(RD8)
                                                .addComponent(RD11))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(imageDistribucion6))
                                        .addComponent(imageDistribucion9, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(RD5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(imageDistribucion2)
                                            .addGap(21, 21, 21)
                                            .addComponent(RN2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(imageNucleo)
                                            .addGap(47, 47, 47)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(RD2)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(imageServidor1)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(SC)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(imageUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(55, 55, 55))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(imageDistribucion11)
                                                .addGap(18, 18, 18)
                                                .addComponent(RD3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(imageDistribucion3)
                                                .addGap(31, 31, 31)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(SE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(imageDistribucion10)
                                                .addComponent(imageDistribucion5))
                                            .addGap(22, 22, 22)
                                            .addComponent(RD10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(imageDistribucion7)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(RD12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(imageDistribucion8))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(imageServidor2)
                                                .addComponent(imageUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(82, 82, 82)
                                    .addComponent(imageServidor4))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(SA)
                                                .addComponent(SD, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(imageUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(imageUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(imageServidor6, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addComponent(imageServidor, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(198, 198, 198)
                                            .addComponent(SF)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(imageUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(imageServidor3)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(imageNucleo2)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(SB)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(imageUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel RD1;
    public javax.swing.JLabel RD10;
    public javax.swing.JLabel RD11;
    public javax.swing.JLabel RD12;
    public javax.swing.JLabel RD2;
    public javax.swing.JLabel RD3;
    public javax.swing.JLabel RD4;
    public javax.swing.JLabel RD5;
    public javax.swing.JLabel RD6;
    public javax.swing.JLabel RD7;
    public javax.swing.JLabel RD8;
    public javax.swing.JLabel RD9;
    public javax.swing.JLabel RN1;
    public javax.swing.JLabel RN2;
    public javax.swing.JLabel RN3;
    public javax.swing.JLabel SA;
    public javax.swing.JLabel SB;
    public javax.swing.JLabel SC;
    public javax.swing.JLabel SD;
    public javax.swing.JLabel SE;
    public javax.swing.JLabel SF;
    public javax.swing.JComboBox<String> comboBoxDestino;
    public javax.swing.JComboBox<String> comboBoxOrigen;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    public javax.swing.JLabel imageDistribucion;
    public javax.swing.JLabel imageDistribucion1;
    public javax.swing.JLabel imageDistribucion10;
    public javax.swing.JLabel imageDistribucion11;
    public javax.swing.JLabel imageDistribucion2;
    public javax.swing.JLabel imageDistribucion3;
    public javax.swing.JLabel imageDistribucion4;
    public javax.swing.JLabel imageDistribucion5;
    public javax.swing.JLabel imageDistribucion6;
    public javax.swing.JLabel imageDistribucion7;
    public javax.swing.JLabel imageDistribucion8;
    public javax.swing.JLabel imageDistribucion9;
    public javax.swing.JLabel imageNucleo;
    public javax.swing.JLabel imageNucleo1;
    public javax.swing.JLabel imageNucleo2;
    public javax.swing.JLabel imageServidor;
    public javax.swing.JLabel imageServidor1;
    public javax.swing.JLabel imageServidor2;
    public javax.swing.JLabel imageServidor3;
    public javax.swing.JLabel imageServidor4;
    public javax.swing.JLabel imageServidor6;
    public javax.swing.JLabel imageUsuario;
    public javax.swing.JLabel imageUsuario1;
    public javax.swing.JLabel imageUsuario2;
    public javax.swing.JLabel imageUsuario3;
    public javax.swing.JLabel imageUsuario4;
    public javax.swing.JLabel imageUsuario5;
    public javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    
}
