/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author tic-asisweb01
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imageUsuario = new javax.swing.JLabel();
        imageUsuario1 = new javax.swing.JLabel();
        imageUsuario2 = new javax.swing.JLabel();
        imageUsuario3 = new javax.swing.JLabel();
        imageUsuario4 = new javax.swing.JLabel();
        imageUsuario5 = new javax.swing.JLabel();
        imageServidor = new javax.swing.JLabel();
        imageServidor1 = new javax.swing.JLabel();
        imageServidor2 = new javax.swing.JLabel();
        imageServidor3 = new javax.swing.JLabel();
        imageServidor4 = new javax.swing.JLabel();
        imageDistribucion = new javax.swing.JLabel();
        imageServidor6 = new javax.swing.JLabel();
        imageDistribucion1 = new javax.swing.JLabel();
        imageDistribucion2 = new javax.swing.JLabel();
        imageDistribucion3 = new javax.swing.JLabel();
        imageDistribucion4 = new javax.swing.JLabel();
        imageDistribucion5 = new javax.swing.JLabel();
        imageDistribucion6 = new javax.swing.JLabel();
        imageDistribucion7 = new javax.swing.JLabel();
        imageDistribucion8 = new javax.swing.JLabel();
        imageDistribucion9 = new javax.swing.JLabel();
        imageNucleo = new javax.swing.JLabel();
        imageDistribucion11 = new javax.swing.JLabel();
        imageNucleo1 = new javax.swing.JLabel();
        imageNucleo2 = new javax.swing.JLabel();
        imageDistribucion10 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 0), new java.awt.Dimension(200, 32767));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        RD1 = new javax.swing.JLabel();
        RD2 = new javax.swing.JLabel();
        RD3 = new javax.swing.JLabel();
        RD4 = new javax.swing.JLabel();
        RD5 = new javax.swing.JLabel();
        RD6 = new javax.swing.JLabel();
        RD7 = new javax.swing.JLabel();
        RD8 = new javax.swing.JLabel();
        RD9 = new javax.swing.JLabel();
        RD10 = new javax.swing.JLabel();
        RD11 = new javax.swing.JLabel();
        RD12 = new javax.swing.JLabel();
        RN1 = new javax.swing.JLabel();
        RN2 = new javax.swing.JLabel();
        RN3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageUsuario3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageUsuario4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageUsuario5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Usuario.png"))); // NOI18N

        imageServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageServidor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageServidor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageServidor3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageServidor4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageDistribucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageServidor6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Servidor.png"))); // NOI18N

        imageDistribucion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageDistribucion9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageNucleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Nucleo.png"))); // NOI18N

        imageDistribucion11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        imageNucleo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Nucleo.png"))); // NOI18N

        imageNucleo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Nucleo.png"))); // NOI18N

        imageDistribucion10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Distribución.png"))); // NOI18N

        jLabel2.setText("Usuario A");

        jLabel3.setText("Usuario B");

        jLabel4.setText("Usuario C");

        jLabel5.setText("Usuario D");

        jLabel6.setText("Usuario E");

        jLabel7.setText("Usuario F");

        RD1.setText("RD1");

        RD2.setText("RD2");

        RD3.setText("RD3");

        RD4.setText("RD4");

        RD5.setText("RD5");

        RD6.setText("RD6");

        RD7.setText("RD7");

        RD8.setText("RD8");

        RD9.setText("RD9");

        RD10.setText("RD10");

        RD11.setText("RD12");

        RD12.setText("RD11");

        RN1.setText("RN1");

        RN2.setText("RN2");

        RN3.setText("RN3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(imageUsuario5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(imageUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(19, 19, 19)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageServidor3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RD2)
                                        .addGap(76, 76, 76))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(imageNucleo2)
                                            .addComponent(imageDistribucion11))
                                        .addGap(63, 63, 63)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageDistribucion2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RD5)
                                        .addGap(19, 19, 19))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RN2)
                                        .addGap(13, 13, 13))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imageServidor1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(imageDistribucion3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(RD3))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RN1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(imageDistribucion1)))))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageNucleo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RD4)
                                        .addGap(15, 15, 15))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(imageUsuario2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(imageServidor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(158, 158, 158)
                                        .addComponent(RD1)))))
                        .addGap(42, 42, 42)
                        .addComponent(imageDistribucion4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(imageDistribucion6))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(imageDistribucion10)
                                        .addComponent(imageDistribucion)
                                        .addComponent(imageNucleo1)
                                        .addComponent(RD8)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(RN3)
                                    .addGap(14, 14, 14)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(55, 55, 55)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(imageDistribucion8)
                                                .addComponent(imageDistribucion7)
                                                .addComponent(imageDistribucion5)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(RD10))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(RD11)))
                                    .addGap(68, 68, 68))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(imageDistribucion9)
                                    .addGap(60, 60, 60)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(imageServidor2)
                                    .addComponent(imageServidor4))
                                .addComponent(imageServidor6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(RD6)
                            .addGap(82, 82, 82)
                            .addComponent(RD9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(RD7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(imageUsuario1)
                                .addComponent(imageUsuario3)
                                .addComponent(imageUsuario4))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(74, 74, 74))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(587, Short.MAX_VALUE)
                    .addComponent(RD12)
                    .addGap(251, 251, 251)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RD6)
                    .addComponent(RD9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageDistribucion5)
                                .addGap(22, 22, 22)
                                .addComponent(RD10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageDistribucion7)
                                .addGap(48, 48, 48)
                                .addComponent(imageDistribucion8)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(RN1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(imageNucleo2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(imageServidor6)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel2)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jLabel5)
                                                            .addGap(2, 2, 2)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(imageUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(imageUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(imageServidor, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel6)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imageUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imageUsuario4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imageServidor2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(imageServidor3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(43, 43, 43)))
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imageServidor4)
                            .addComponent(imageUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(imageDistribucion10)
                                .addGap(18, 18, 18)
                                .addComponent(RN3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageNucleo1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RD1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(118, 118, 118))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(RD4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(imageDistribucion4)))
                                    .addComponent(imageDistribucion1))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RD7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageDistribucion)
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RD8)
                                            .addComponent(RD11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageDistribucion6))
                                    .addComponent(imageDistribucion9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RD5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageDistribucion2)
                                        .addGap(21, 21, 21)
                                        .addComponent(RN2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageNucleo)
                                        .addGap(53, 53, 53))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(RD2)
                                .addGap(4, 4, 4)
                                .addComponent(imageDistribucion11)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(imageServidor1)
                                            .addComponent(imageUsuario5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(RD3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(imageDistribucion3)))))
                        .addGap(28, 28, 28))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(RD12)
                    .addContainerGap(230, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel RD1;
    public javax.swing.JLabel RD10;
    public javax.swing.JLabel RD11;
    public javax.swing.JLabel RD12;
    public javax.swing.JLabel RD2;
    public javax.swing.JLabel RD3;
    public javax.swing.JLabel RD4;
    public javax.swing.JLabel RD5;
    public javax.swing.JLabel RD6;
    public javax.swing.JLabel RD7;
    public javax.swing.JLabel RD8;
    public javax.swing.JLabel RD9;
    public javax.swing.JLabel RN1;
    public javax.swing.JLabel RN2;
    public javax.swing.JLabel RN3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    public javax.swing.JLabel imageDistribucion;
    public javax.swing.JLabel imageDistribucion1;
    public javax.swing.JLabel imageDistribucion10;
    public javax.swing.JLabel imageDistribucion11;
    public javax.swing.JLabel imageDistribucion2;
    public javax.swing.JLabel imageDistribucion3;
    public javax.swing.JLabel imageDistribucion4;
    public javax.swing.JLabel imageDistribucion5;
    public javax.swing.JLabel imageDistribucion6;
    public javax.swing.JLabel imageDistribucion7;
    public javax.swing.JLabel imageDistribucion8;
    public javax.swing.JLabel imageDistribucion9;
    public javax.swing.JLabel imageNucleo;
    public javax.swing.JLabel imageNucleo1;
    public javax.swing.JLabel imageNucleo2;
    public javax.swing.JLabel imageServidor;
    public javax.swing.JLabel imageServidor1;
    public javax.swing.JLabel imageServidor2;
    public javax.swing.JLabel imageServidor3;
    public javax.swing.JLabel imageServidor4;
    public javax.swing.JLabel imageServidor6;
    public javax.swing.JLabel imageUsuario;
    public javax.swing.JLabel imageUsuario1;
    public javax.swing.JLabel imageUsuario2;
    public javax.swing.JLabel imageUsuario3;
    public javax.swing.JLabel imageUsuario4;
    public javax.swing.JLabel imageUsuario5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
